# Generated by Django 4.2.5 on 2023-09-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistit', '0002_giftitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftitem',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
